name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t arturshved/multi-client ./client
      - run: docker build -t arturshved/multi-nginx ./nginx
      - run: docker build -t arturshved/multi-server ./server
      - run: docker build -t arturshved/multi-worker ./worker
      - run: docker build -t arturshved/react-test -f ./client/Dockerfile.dev ./client

      - run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker run -e CI=true arturshved/react-test npm test

      - run: docker push arturshved/multi-client
      - run: docker push arturshved/multi-nginx
      - run: docker push arturshved/multi-server
      - run: docker push arturshved/multi-worker
